
name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      run: echo Test
      # uses: actions/setup-python@v2
      # with:
      #   python-version: 3.7
